[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "rmshared"
readme = "README.md"
dynamic = ["version"]
authors = [
    {name = "CordiS", email = "cordis@rebelmouse.com"}
]
description = "RebelMouse shared library"
license = {text = "Apache 2.0"}
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Apache Software License",
]
requires-python = ">=3.11"
dependencies = [
    "lark==1.3.1",
    "orjson>=3.10,<3.12",
    "aiohttp==3.13.5",
    "enumclasses @ https://github.com/RebelMouseTeam/enumclasses/archive/refs/tags/v1.1.7.tar.gz"
]

[project.optional-dependencies]
dev = [
    "mock==5.1.0",
    "faker==24.14.0",
    "pytest==8.2.0",
    "flake8==7.0.0"
]

[project.urls]
Homepage = "https://github.com/RebelMouseTeam/rmshared"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.hatch.build.targets.wheel]
packages = ["rmshared"]
exclude = ["rmshared/**/tests"]
