from rmshared.content.taxonomy import core

Id = core.aliases.fields.System('post-id')
Type = core.aliases.fields.System('post-type')
Status = core.aliases.fields.System('post-status')
IsPrivate = core.aliases.fields.System('post-is-private')
IsSuspicious = core.aliases.fields.System('post-is-suspicious')
IsExcludedFromSearch = core.aliases.fields.System('post-is-excluded-from-search')
ModifiedAt = core.aliases.fields.System('post-modified-at')
ScheduledAt = core.aliases.fields.System('post-scheduled-at')
PublishedAt = core.aliases.fields.System('post-published-at')
Title = core.aliases.fields.System('post-title')
Subtitle = core.aliases.fields.System('post-subtitle')
Body = core.aliases.fields.System('post-body')
PrimaryTag = core.aliases.fields.System('post-primary-tag')
RegularTag = core.aliases.fields.System('post-regular-tag')
PrimarySection = core.aliases.fields.System('post-primary-section')
RegularSection = core.aliases.fields.System('post-regular-section')
Community = core.aliases.fields.System('post-community')
Author = core.aliases.fields.System('post-author')
Stage = core.aliases.fields.System('post-stage')
PageLayout = core.aliases.fields.System('post-page-layout')
EditorLayout = core.aliases.fields.System('post-editor-layout')
CustomField = core.aliases.fields.Custom('post-custom-field')
PageViewsCount = core.aliases.fields.System('post-page-views-count')  # TODO: Replace with events/metrics
